### ISSUE TITLE
running sample errors

### ISSUE THREAD

**Issue by kevkevinpal** [p2pderivatives/rust-dlc#192] opened 2023-12-27 16:49 UTC
I tried running the sample but ran into a few issues

---

1). When trying to start alice with her configuration I had a SSL cert issue but it seemed this website's certificate was expired `https://oracle.p2pderivatives.io/`

I resolved this by running `https://github.com/p2pderivatives/p2pderivatives-oracle` locally

---

2). After starting up alice and bob I ran this command to try and send offer `offercontract 024b5bc3c328d92fdf30421093b214b4099b78617e9195afd2106f444b670c731d@127.0.0.1:9000 ./examples/contracts/numerical_contract_input.json`

I ran into this error 
```
> offercontract 024b5bc3c328d92fdf30421093b214b4099b78617e9195afd2106f444b670c731d@127.0.0.1:9000 ./examples/contracts/numerical_contract_input.json
Checking for messages
connecting to peer 024b5bc3c328d92fdf30421093b214b4099b78617e9195afd2106f444b670c731d
ERROR: Peer disconnected before we finished the handshake
thread 'tokio-runtime-worker' panicked at sample/src/cli.rs:203:38:
Error sending offer: InvalidParameters("Unknown oracle public key")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at sample/src/cli.rs:216:22:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(27), ...)
```

I then tried using the `connectpeer` command but then got this error
```
> connectpeer 024b5bc3c328d92fdf30421093b214b4099b78617e9195afd2106f444b670c731d@localhost:9000
Checking for messages
ERROR: Peer disconnected before we finished the handshake
```

---

Now I am stuck at this point any guidance would be helpful, I can also open a PR for any changes I need to make to run the sample successfully for anyone in the future

**Comment by kevkevinpal** [comment] 2023-12-27 17:06
its probably good to add that I'm running on a 2019 Macbook pro

**Comment by Tibo-lg** [comment] 2024-01-11 01:03
Finally found the cause of the connection issue, will be pushing a PR to fix everything soonish.

**Comment by Tibo-lg** [comment] 2024-01-17 00:38
Unfortunately I found another issue within LDK which prevents running the sample properly. Will need to wait for https://github.com/lightningdevkit/rust-lightning/pull/2832 to be merged and a new release of LDK.

**Closed** 2024-02-22 02:41 UTC
