### ISSUE TITLE
Sample crashes when offering contract to a DLC node

### ISSUE THREAD

**Issue by MusigMaestro** [p2pderivatives/rust-dlc#229] opened 2024-06-28 09:38 UTC
The sample code which illustrates how various parts of the library comes together is failing when offering a contract to Alice.

Conditions to reproduce the issue: Running the sample as illustrated in the repo
Environment: Ubuntu 22.04 LTS

Error on Bob's instance after offering contract:
```
Checking for messages
SUCCESS: connected to peer 02ba27499250af5f64f8aeeafffba905799ffda165bd8de335e182c4fc7c6ef6d9
thread 'tokio-runtime-worker' panicked at sample/src/cli.rs:202:38:
Error sending offer: OracleError("error decoding response body: missing field `announcementSignature` at line 1 column 233")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at sample/src/cli.rs:215:22:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(17), ...)
```

**Comment by Tibo-lg** [comment] 2024-07-02 11:47
@MusigMaestro I just ran the sample on the latest master branch and did not encounter any issue. Did you make any modification to the code or the configs that might lead to this issue?

**Comment by Tibo-lg** [comment] 2024-07-11 01:22
@MusigMaestro as I can't reproduce your issue I'll close this. If you have more details to provide on how to reproduce it feel free to re-open it.

**Closed by Tibo-lg** 2024-07-11 01:22 UTC
